// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXMe2ILD0Zb59Qtdu-X9ZyR-tGkwR4qw',
    appId: '1:639102444061:web:c8b2efa6a6ce8afddd9cf4',
    messagingSenderId: '639102444061',
    projectId: 'e-commerce-6de41',
    authDomain: 'e-commerce-6de41.firebaseapp.com',
    storageBucket: 'e-commerce-6de41.appspot.com',
    measurementId: 'G-8MR84383VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7vjEiJDJHMp-U7wZmkZgPomq3Z9Ytf7o',
    appId: '1:639102444061:android:8e695261b076f1a3dd9cf4',
    messagingSenderId: '639102444061',
    projectId: 'e-commerce-6de41',
    storageBucket: 'e-commerce-6de41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRU8SGW45uCzIORbn0wNk14m5ySxcohA',
    appId: '1:639102444061:ios:b6be2add97d27f41dd9cf4',
    messagingSenderId: '639102444061',
    projectId: 'e-commerce-6de41',
    storageBucket: 'e-commerce-6de41.appspot.com',
    iosClientId: '639102444061-1p2e2kd1evl8gbdli0kbd0sutko1qk3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByRU8SGW45uCzIORbn0wNk14m5ySxcohA',
    appId: '1:639102444061:ios:d8232132884c94b7dd9cf4',
    messagingSenderId: '639102444061',
    projectId: 'e-commerce-6de41',
    storageBucket: 'e-commerce-6de41.appspot.com',
    iosClientId: '639102444061-6iak1dahj3b2c6q24uaegfumupgtkv7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
